AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Package & Deploy Serverless Functions using SAM Template & Cloudformation (via AWS CLI)
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs12.7
    Timeout: 5
Resources:
  loggerFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: logging/
      Handler: logger.handler
      Timeout: 3  # this will overwrite Globals section Timeout property
  addFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: operation/
      Handler: add.handler
  
  # the following way is to create an API in an explicit way (definition of the API is within the swagger file)
  dummyTestAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dummyTest
      DefinitionUri: someDummySwaggerFile.yml
