AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Package & Deploy Serverless Functions using SAM Template & Cloudformation (via AWS CLI)
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs12.7
    Timeout: 5
Resources:
  loggerFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: logging/
      Handler: logger.handler
      Timeout: 3  # this will overwrite Globals section Timeout property
      # create API implicitly
      Events:
        GetLogs:
          Type: Api
          Properties:
            Path: /logs
            Method: get

  addFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: operation/
      Handler: add.handler
      # create API implicitly
      Events:
        PostAdd:
          Type: Api
          Properties:
            Path: /add
            Method: post