AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Package & Deploy Serverless Functions using SAM Template & Cloudformation (via AWS CLI)
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs12.7
    Timeout: 5
Resources:
  loggerFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: logging/
      Handler: logger.handler
      Timeout: 3  # this will overwrite Globals section Timeout property
      # create API implicitly
      Events:
        GetLogs:
          Type: Api
          Properties:
            Path: /logs
            Method: get
        # add S3 file upload event trigger
        MyFileUpload:
          Type: S3
          Properties:
            Bucket: !Ref MyBucketSAMInit  # reference to MyBucketSAMInit
            Events: s3:ObjectCreated:*    # event triggered when file is uploaded to S3 bucket

  # reference of the bucket of MyFileUpload event trigger
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_S3.html
  MyBucketSAMInit:
    Type: AWS::S3::Bucket

  addFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: operation/
      Handler: add.handler
      # create API implicitly
      Events:
        PostAdd:
          Type: Api
          Properties:
            Path: /add
            Method: post